apiVersion: v1
kind: ServiceAccount
metadata:
  name: crypto-api-sa
  namespace: crypto-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crypto-worker-sa
  namespace: crypto-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crypto-app-read-role
  namespace: crypto-platform
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crypto-api-rolebinding
  namespace: crypto-platform
subjects:
  - kind: ServiceAccount
    name: crypto-api-sa
    namespace: crypto-platform
roleRef:
  kind: Role
  name: crypto-app-read-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crypto-worker-rolebinding
  namespace: crypto-platform
subjects:
  - kind: ServiceAccount
    name: crypto-worker-sa
    namespace: crypto-platform
roleRef:
  kind: Role
  name: crypto-app-read-role
  apiGroup: rbac.authorization.k8s.io