name: CI/CD Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        run: |
          docker build -t khalil1545/crypto-api:latest ./services/api
          docker push khalil1545/crypto-api:latest

      - name: Build and push Worker image
        run: |
          docker build -t khalil1545/crypto-worker:latest ./services/worker
          docker push khalil1545/crypto-worker:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name crypto-platform-eks

      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/redis-deployment.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/services.yaml
          kubectl apply -f k8s/api-deployment.yaml
          kubectl apply -f k8s/worker-deployment.yaml
          kubectl apply -f k8s/hpa.yaml

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment/crypto-api -n crypto-platform
          kubectl rollout restart deployment/crypto-worker -n crypto-platform

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/crypto-api -n crypto-platform --timeout=180s
          kubectl rollout status deployment/crypto-worker -n crypto-platform --timeout=180s

      - name: Smoke test health endpoint
        run: |
          sleep 30
          curl -f http://ae55e7c83580346679cf02f3afb46863-1159999103.us-east-1.elb.amazonaws.com:8000/health